# The Substrate — export: substrate.blend -> GLB -> gltfpack (meshopt +
# KTX2, node names kept) -> public/assets/substrate.glb, and regenerate
# lib/scene/anchors.generated.ts from out/anchors.json.
# Run: blender -b out/substrate.blend -P export.py
#
# Deltas vs master plan Task 6 (P1 report):
# - use_visible=True: the exporter ships viewport-hidden objects by default,
#   so hiding the tracelane bake geometry is not enough to exclude it.
# - courier survival: the exporter drops emissiveTexture when Emission
#   Strength is 0, which would silently lose the trace mask from the GLB.
#   Strength is forced to 1.0 in this session only (the .blend on disk
#   keeps 0; the runtime replaces the material and keys on emissiveMap).
# - anchors.generated.ts additionally exports DISTRICTS (director GO item:
#   district centroids for the Director's act-3 card anchoring).
import json
import os
import subprocess
import sys

import bpy

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "out")
REPO = os.path.abspath(os.path.join(ROOT, "..", "..", ".."))
RAW = os.path.join(OUT, "substrate_raw.glb")
FINAL = os.path.join(REPO, "public", "assets", "substrate.glb")

os.makedirs(os.path.dirname(FINAL), exist_ok=True)

# bake-only geometry out of the export
for o in bpy.data.objects:
    if o.name.startswith("tracelane_"):
        o.hide_set(True)
        o.hide_render = True

# courier survival (see header)
traced = bpy.data.materials.get("mt_solder_traced")
if traced:
    pb = traced.node_tree.nodes.get("Principled BSDF")
    if pb and pb.inputs.get("Emission Strength"):
        pb.inputs["Emission Strength"].default_value = 1.0

bpy.ops.export_scene.gltf(
    filepath=RAW,
    export_format="GLB",
    export_yup=True,
    export_apply=True,
    export_animations=False,
    export_extras=True,
    use_visible=True,
)

# meshopt (-cc) + KTX2 (-tc); -kn keeps node names (ihs, socket_anchor,
# dieblock_* are the runtime contract). If the validator fails the 6MB
# budget, add "-tq", "4". If the trace mask shows banding in review,
# switch "-tc" to "-tu" (UASTC) and re-validate.
# The npm wasm gltfpack ships WITHOUT BasisU — the native binary
# (v2/tools/gltfpack/, meshoptimizer v0.25 release) is required for -tc.
GLTFPACK = os.path.join(ROOT, "..", "gltfpack", "gltfpack")
if not os.path.exists(GLTFPACK):
    raise SystemExit(
        "native gltfpack missing: download gltfpack-ubuntu.zip from the "
        "meshoptimizer v0.25 release into v2/tools/gltfpack/"
    )
subprocess.run(
    [GLTFPACK, "-i", RAW, "-o", FINAL, "-cc", "-kn", "-tc", "-tq", "4", "-vp", "12", "-vt", "10", "-vn", "8"],
    check=True,
)

with open(os.path.join(OUT, "anchors.json")) as f:
    a = json.load(f)


def v3(v):
    return "[%s, %s, %s]" % (v[0], v[1], v[2])


lanes_ts = ",\n  ".join(
    "[%s]" % ", ".join(v3(p) for p in lane) for lane in a["lanes"]
)
districts_ts = ",\n  ".join(
    "{ id: '%s', center: %s, extent: [%s, %s] }"
    % (d["id"], v3(d["center"]), d["extent"][0], d["extent"][1])
    for d in a.get("districts", [])
)

ts = """/* GENERATED by v2/tools/blender-substrate/export.py — do not hand-edit.
   World anchors for The Substrate (glTF Y-up, scene units). Regenerate with
   v2/tools/blender-substrate/run_all.sh. Hero asset: %s. */

export const BOARD_MIN = %s as const
export const BOARD_MAX = %s as const
export const SURFACE_Y = %s
export const SOCKET_POS = %s as const
export const SOCKET_POS_DIE = %s as const
export const DIE_CENTER = %s as const
export const DIE_Y = %s

/* Trace-pulse lane polylines (world space), from the mask bake. Lane 5 is
   the edge-to-edge finale lane (SPEC §4 Act 6). */
export const LANES = [
  %s,
] as const

/* Component-district centroids for act-3 card anchoring (director GO). */
export const DISTRICTS = [
  %s,
] as const
""" % (
    a.get("hero", "unknown"),
    v3(a["boardMin"]), v3(a["boardMax"]), a["surfaceY"],
    v3(a["socketPos"]), v3(a["socketPosDie"]), v3(a["dieCenter"]),
    a["dieY"], lanes_ts, districts_ts,
)

gen = os.path.join(REPO, "lib", "scene", "anchors.generated.ts")
with open(gen, "w") as f:
    f.write(ts)
print("DONE export: %s + anchors.generated.ts" % FINAL)
sys.exit(0)
