#!/usr/bin/env python3
# Generate lib/scene/grade.generated.ts from grade/acts.json (GRADE.md is
# the contract; acts.json is the single source of truth the offline grader
# and the runtime GradeEffect share). Plain python3 — no Blender needed.
# Run: python3 gen_grade_ts.py   (also wired into run_all.sh)
import json
import os
import subprocess

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(ROOT, "..", "..", ".."))
SRC = os.path.join(ROOT, "grade", "acts.json")
DEST = os.path.join(REPO, "lib", "scene", "grade.generated.ts")

with open(SRC) as f:
    acts = json.load(f)


def v(x):
    return json.dumps(x)


entries = []
for key in sorted(acts.keys(), key=int):
    a = acts[key]
    pts = ", ".join("[%s, %s]" % (p[0], p[1]) for p in a["blueCurve"])
    entries.append(
        """  {
    name: %s,
    temp: %s,
    sat: %s,
    exp: %s,
    contrast: %s,
    pivot: %s,
    floor: %s,
    halation: %s,
    grain: %s,
    vignette: %s,
    blueCurve: [%s],
  },"""
        % (
            v(a["name"]), v(a["temp"]), v(a["sat"]), v(a["exp"]),
            v(a["contrast"]), v(a["pivot"]), v(a["floor"]), v(a["halation"]),
            v(a["grain"]), v(a["vignette"]), pts,
        )
    )

ts = """/* GENERATED by v2/tools/blender-substrate/gen_grade_ts.py from
   grade/acts.json — do not hand-edit (GRADE.md is the contract; the
   offline grader and this runtime table share the same numbers). */

export interface GradeAct {
  name: string
  temp: number
  sat: number
  exp: number
  contrast: number
  pivot: number
  floor: number
  halation: number
  grain: number
  vignette: number
  blueCurve: readonly (readonly [number, number])[]
}

export const GRADE_ACTS: readonly GradeAct[] = [
%s
]
""" % "\n".join(entries)

with open(DEST, "w") as f:
    f.write(ts)
try:
    subprocess.run(
        ["bunx", "--bun", "@biomejs/biome", "check", "--write", DEST],
        check=False, cwd=REPO, capture_output=True,
    )
except Exception:
    pass
print("WROTE %s (%d acts)" % (DEST, len(acts)))
