/* GENERATED by v2/tools/blender-substrate/export.py — do not hand-edit.
   World anchors for The Substrate (glTF Y-up, scene units). Regenerate with
   v2/tools/blender-substrate/run_all.sh. Hero asset: strix. */

export const BOARD_MIN = [-9.0194, 0.55, 9.1759] as const
export const BOARD_MAX = [8.4868, 2.7604, -9.5738] as const
export const SURFACE_Y = 1.0824
export const SOCKET_POS = [1.2217, 1.0824, -3.9114] as const
export const SOCKET_POS_DIE = [1.2217, -39.8529, -3.9114] as const
export const DIE_CENTER = [1.2217, -39.9264, -3.9114] as const
export const DIE_Y = -40.0

/* Trace-pulse lane polylines (world space), from the mask bake. Lane 5 is
   the edge-to-edge finale lane (SPEC §4 Act 6). */
export const LANES = [
  [[-0.279, 0.9159, -5.46], [-0.1924, 0.9159, -4.32], [0.4329, 0.9159, -3.36], [0.7504, 0.9159, -2.58]],
  [[3.2419, 0.9159, -5.148], [3.2419, 0.9159, -2.688], [2.1164, 0.9159, -2.52], [1.2506, 0.9159, -2.376]],
  [[-4.5214, 0.9159, 3.96], [-4.5214, 0.9159, 0.6], [-3.848, 0.9159, -0.6], [-2.405, 0.9159, -1.44], [-0.481, 0.9159, -2.04], [0.5291, 0.9159, -2.316]],
  [[2.3761, 0.9159, 4.08], [2.3761, 0.9159, 2.484], [1.5392, 0.9159, 0.6], [1.1063, 0.9159, -1.2], [0.8947, 0.9159, -2.1]],
  [[-3.848, 0.9159, 1.524], [-1.443, 0.9159, 1.524], [0.0, 0.9159, 0.96], [0.6253, 0.9159, -0.6], [0.7888, 0.9159, -1.98]],
  [[-4.7138, 0.9159, -2.376], [-1.924, 0.9159, -2.376], [0.8177, 0.9159, -2.376], [2.886, 0.9159, -2.4], [4.7138, 0.9159, -2.4]],
] as const

/* Component-district centroids for act-3 card anchoring (director GO). */
export const DISTRICTS = [
  { id: 'socket', center: [0.8184, 1.1829, -2.3722], extent: [1.1135, 1.1135] },
  { id: 'vrm', center: [-0.2773, 1.1829, -5.2762], extent: [2.4497, 0.9799] },
  { id: 'dimm', center: [3.2413, 1.1829, -2.4257], extent: [0.7126, 3.0287] },
  { id: 'chipset', center: [2.3728, 1.1829, 2.4782], extent: [1.737, 1.6925] },
  { id: 'm2', center: [0.1681, 1.1829, 0.2022], extent: [2.0043, 0.7126] },
  { id: 'io', center: [-4.7757, 1.1829, -3.1383], extent: [0.6235, 2.895] },
  { id: 'pcie', center: [-1.168, 1.1829, 2.6519], extent: [2.895, 1.7816] },
] as const
