/* GENERATED by v2/tools/blender-substrate/gen_grade_ts.py from
   grade/acts.json — do not hand-edit (GRADE.md is the contract; the
   offline grader and this runtime table share the same numbers). */

export interface GradeAct {
  name: string
  temp: number
  sat: number
  exp: number
  contrast: number
  pivot: number
  floor: number
  halation: number
  grain: number
  vignette: number
  blueCurve: readonly (readonly [number, number])[]
}

export const GRADE_ACTS: readonly GradeAct[] = [
  {
    name: 'Hero',
    temp: 0.14,
    sat: 1.0,
    exp: -0.25,
    contrast: 0.38,
    pivot: 0.35,
    floor: 0.06,
    halation: 0.3,
    grain: 0.016,
    vignette: 0.0,
    blueCurve: [
      [0.0, 0.015],
      [0.2, 0.21],
      [0.5, 0.485],
      [0.8, 0.815],
      [1.0, 0.99],
    ],
  },
  {
    name: 'Statement',
    temp: -0.1,
    sat: 0.9,
    exp: -0.2,
    contrast: 0.34,
    pivot: 0.38,
    floor: 0.07,
    halation: 0.25,
    grain: 0.016,
    vignette: 0.0,
    blueCurve: [
      [0.0, 0.03],
      [0.2, 0.23],
      [0.5, 0.5],
      [0.8, 0.82],
      [1.0, 1.0],
    ],
  },
  {
    name: 'Work',
    temp: 0.0,
    sat: 1.0,
    exp: -0.25,
    contrast: 0.36,
    pivot: 0.36,
    floor: 0.06,
    halation: 0.3,
    grain: 0.016,
    vignette: 0.0,
    blueCurve: [
      [0.0, 0.012],
      [0.2, 0.205],
      [0.5, 0.49],
      [0.8, 0.81],
      [1.0, 0.995],
    ],
  },
  {
    name: 'Evidence',
    temp: 0.08,
    sat: 1.05,
    exp: -0.25,
    contrast: 0.4,
    pivot: 0.42,
    floor: 0.055,
    halation: 0.28,
    grain: 0.016,
    vignette: 0.0,
    blueCurve: [
      [0.0, 0.01],
      [0.2, 0.2],
      [0.5, 0.48],
      [0.8, 0.8],
      [1.0, 0.98],
    ],
  },
  {
    name: 'About',
    temp: 0.0,
    sat: 1.0,
    exp: -0.3,
    contrast: 0.42,
    pivot: 0.36,
    floor: 0.065,
    halation: 0.3,
    grain: 0.018,
    vignette: 0.1,
    blueCurve: [
      [0.0, 0.02],
      [0.25, 0.25],
      [0.5, 0.49],
      [0.75, 0.77],
      [1.0, 0.99],
    ],
  },
  {
    name: 'Contact',
    temp: 0.2,
    sat: 1.0,
    exp: -0.2,
    contrast: 0.36,
    pivot: 0.38,
    floor: 0.05,
    halation: 0.4,
    grain: 0.016,
    vignette: 0.0,
    blueCurve: [
      [0.0, 0.02],
      [0.2, 0.2],
      [0.5, 0.47],
      [0.8, 0.78],
      [1.0, 0.96],
    ],
  },
]
